pipelines:
  - name: pre-commit
    entrypoint: PreCommit
    on:
      pre_commit: {}

  - name: pre-push
    entrypoint: PrePush
    on:
      pre_push: {}

  - name: release-modules
    entrypoint: ReleaseModules
