package checks

import (
	"os"
	"path/filepath"
	"testing"
)

const generatedMarker = "// Code generated by ledgergen. DO NOT EDIT.\n"

const bodyWithDisallowedComment = `package ledger

func Load() int {
	// load the rows
	return 0
}
`

func writeGoFile(t *testing.T, name, contents string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestCheckCommentsFileGeneratedMarker(t *testing.T) {
	cases := []struct {
		name     string
		contents string
		want     int
	}{
		{"detached header", generatedMarker + "\n" + bodyWithDisallowedComment, 0},
		{"attached header", generatedMarker + bodyWithDisallowedComment, 0},
		{"marker below the package clause", bodyWithDisallowedComment + "\n" + generatedMarker, 2},
		{"handwritten", bodyWithDisallowedComment, 1},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := checkCommentsFile(writeGoFile(t, "zz_generated.go", tc.contents))
			if err != nil {
				t.Fatal(err)
			}
			if len(got) != tc.want {
				t.Fatalf("got %d violation(s), want %d: %+v", len(got), tc.want, got)
			}
		})
	}
}
